### ISSUE TITLE
Sección 2 - services

### ISSUE THREAD

**Issue by AlbertDeHoz** [AlbertDeHoz/semana-1-141#7]
Sección de servicios:Dividir en ancho del sitio en 3 partes y en cada parte se deberá incluir un servicio. Cada servicio debe contar con una breve descripción, un logo, ícono o imagen que lo identifique y un enlace al detalle de los servicios. El elemento donde están los servicios debe de tener un id=”services”

**Comment by nicolayrivera75** [comment]
En proceso de desarrollo del requerimiento según lo solicitado en la guía y con lo visto en la clase dehoy
